export const SUPPORTED_LANG = [
    { identifier: "EN", name: "English" },
    { identifier: "HI", name: "हिंदी" },
    { identifier: "GJ", name: "गुजराती" },
    { identifier: "ES", name: "स्पैनिश" },
];

export const lang = {
    EN: {
        loginText: "Sign In",
        signupText: "Sign up",
        rememberMe: "Remember me",
        needHelp: "Need help?",
        bodyText: "Enjoy big movies, hit series and more",
        getStartedBtn: "Get Started",
        gptSearchPlaceholder: "What would you like to watch today",
        search: "Search",
        FullNamePlaceholder: "Full Name",
        EmailAddressPlaceholder: "Email address",
        PasswordPlaceholder: "Password",
    },
    HI: {
        loginText: "साइन इन करें",
        signupText: "साइन अप करें",
        rememberMe: "याद रखें",
        needHelp: "आपको मदद चाहिए?",
        bodyText: "बड़ी फ़िल्में, हिट सीरीज़ और बहुत कुछ का आनंद लें",
        getStartedBtn: "शुरू करें",
        gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे",
        search: "खोजे",
        FullNamePlaceholder: "पूरा नाम",
        EmailAddressPlaceholder: "ईमेल एड्रेस",
        PasswordPlaceholder: "पासवर्ड",
    },
    GJ: {
        loginText: "પ્રવેશ કરો",
        signupText: "સાઇન અપ કરો",
        rememberMe: "યાદ રાખો",
        needHelp: "મદદ જોઈતી?",
        bodyText: "મોટી મૂવીઝ, હિટ સિરીઝ અને વધુનો આનંદ માણો",
        getStartedBtn: "શરૂ કરો",
        gptSearchPlaceholder: "તમે આજે શું જોવા માંગો છો",
        search: "શોધ",
        FullNamePlaceholder: "પૂરું નામ",
        EmailAddressPlaceholder: "ઇમેઇલ એડ્રેસ",
        PasswordPlaceholder: "પાસવર્ડ",
    },
    ES: {
        loginText: "दाखिल करें",
        signupText: "inscribirse",
        rememberMe: "recordar",
        needHelp: "¿Necesitas ayuda?",
        bodyText: "Disfruta de grandes películas, series exitosas y más",
        getStartedBtn: "Empezar",
        gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
        search: "Buscar",
        FullNamePlaceholder: "nombre completo",
        EmailAddressPlaceholder: "ईमेल एड्रेस",
        PasswordPlaceholder: "Contraseña",
    },
};
